[main]
certname = puppet-master.internal.example.com
server = puppet-master.internal.example.com
environment = production
runinterval = 1h

[master]
storeconfigs = true
storeconfigs_backend = puppetdb
reports = puppetdb
